### ISSUE TITLE
Rebase against SMBIOS3.0

### ISSUE THREAD

**Issue by mjtrangoni** [nima/python-dmidecode#2]
It would be nice to have a rebase against the SMBIOS specification 3.0, actually implemented here [1]

There is some bug fixes and support for new memory types like "LPDDR4", sockets, etc.

Is there any automatic rebase script or is it just made manually? Commt #4ca9576 seems to be the latest rebase made by David Sommerseth against dmidecode v2.11.

[1] git://git.savannah.nongnu.org/dmidecode.git

**Comment by dsommers** [comment]
Hi,

There are no rebase scripts unfortunately.  So it's a fairly untrivial, but needed task.  I am quite swamped these days so I don't have too much time to do such work.  But if you, or anyone else for that matter, are willing to look into it - I will definitely do a review asap.

But it's good to see that upstream dmidecode have moved out of CVS and to git ... that simplifies a few things.

By the way, I have had a few discussions with upstream dmidecode to see if we can agree on a common API for the dmidecode stuff, so we wouldn't need to do this duplicated work.  But such thoughts were not accepted and we were pointed in the direction of the far more complex and heavy libsmi and related packages.  Introducing an API in dmidecode was considered too intrusive and complicating the code too much.

**Comment by Jamstah** [comment]
Looking at that git repo, I can't find a commit that matches what was used as a base. I'm trying to work out what changes were made to upstream for the python module, to see if they'll apply on top of a newer commit.

Do you know if the cvs is still up? Do you know which tag it was from? The version file says 3.12.2, but the latest in the git repo is only 3.1, so I feel it must have forked somewhere.

**Comment by lian-bo** [comment]
This issue has been solved(https://github.com/nima/python-dmidecode/pull/46), so close it.
